name: primeraChamba

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows
    steps:
      - name: RevisionRepo
        run: echo "se está ejecutando el entorno"

      - name: AnalisisRepo
        run: echo "se está analizando el repositorio"

      - name: preparar entorno
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: actualizar pip
        run: |
          python -m pip install --upgrade pip

      - name: instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: ejecutar pruebas
        run: |
          python -m pytest


ls -la

